-- ══════════════════════════════════════════════════════════════
-- HyprZen — Autostart (exec-once)
-- OSD is ZenShell's own (OSD.qml, driven by wpctl/brightnessctl polling).
-- Notifications are likewise owned by the island.
-- ══════════════════════════════════════════════════════════════

-- ── Core System ───────────────────────────────────────────────
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- ── Bar ───────────────────────────────────────────────────────

-- ── Notifications (ZenShell island) & OSD ─────────────────────

-- ── Wallpaper (awww — smooth transitions, updates ~/wallpapers/current) ──

-- ── Idle & Lock ───────────────────────────────────────────────

-- ── Desktop Widgets ───────────────────────────────────────────

-- ── Clipboard ─────────────────────────────────────────────────

-- ── Network tray ──────────────────────────────────────────────

-- ── GTK Theme ─────────────────────────────────────────────────

-- ── Window Switcher ───────────────────────────────────────────

hl.on("hyprland.start", function()
    -- Load hyprpm plugins (scrolloverview, etc.) — must run first
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME")
    hl.exec_cmd("sleep 2 && systemctl --user restart xdg-desktop-portal-hyprland xdg-desktop-portal")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 0.5 && awww img ~/wallpapers/current --transition-type wipe")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/.config/quickshell/dynamic-island/start_all.sh")
    hl.exec_cmd("wl-paste --type text  --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme      'adw-gtk3-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme   'prefer-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme     'Papirus-Dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme   'Bibata-Modern-Ice'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size    24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name      'JetBrainsMono Nerd Font 11'")
end)
