-- ══════════════════════════════════════════════════════════════
-- HyprZen — Keybinds
-- Merged with ZenShell (Quickshell Dynamic Island). All combos
-- below are unique — no clashes between HyprZen and ZenShell.
-- ══════════════════════════════════════════════════════════════

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local S = "SUPER"
local SS = "SUPER + SHIFT"
local SC = "SUPER + CTRL"
local SA = "SUPER + ALT"

-- ── Apps ──────────────────────────────────────────────────────
-- Each binary here must be installed by ../install.sh. These previously bound
-- to librewolf / nautilus / codium, none of which the installer shipped, so
-- SUPER+B, SUPER+E and SUPER+C all silently did nothing on a fresh install.
hl.bind(S .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(S .. " + B", hl.dsp.exec_cmd("firefox"))
hl.bind(S .. " + E", hl.dsp.exec_cmd("thunar"))
hl.bind(S .. " + C", hl.dsp.exec_cmd("codium"))
hl.bind(S .. " + D", hl.dsp.exec_cmd("quickshell ipc -p ~/.config/quickshell/dynamic-island/modules/desktop-widgets call widgets toggle"))

-- ── Launcher / Search ─────────────────────────────────────────
hl.bind(S .. " + SPACE", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh launcher"))
hl.bind(S .. " + comma", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh cheatsheet"))
hl.bind(SA .. " + TAB", hl.dsp.exec_cmd("hyprswitch gui --mod-key alt_l --key tab --close mod-key-release --reverse-key=mod=shift --sort-recent --ignore-workspaces"))

-- ── Clipboard (ZenShell island) ───────────────────────────────
hl.bind(S .. " + V", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh clipboard"))

-- ── Notifications (owned by ZenShell island) ──────────────────
hl.bind(S .. " + N", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh control"))

-- ── Power / Session ───────────────────────────────────────────
-- wlogout comes from the AUR list in install.sh. ZenShell also ships a power
-- menu on SUPER+ESC; both are intentionally available.
hl.bind(S .. " + X", hl.dsp.exec_cmd("wlogout -b 5 -T 350 -B 350"))
hl.bind(SS .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(SS .. " + C", hl.dsp.exec_cmd("~/scripts/caffeine.sh"))
-- ── Theme & Wallpaper (ZenShell island) ───────────────────────
hl.bind(S .. " + T", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh themes"))
hl.bind(S .. " + W", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh wallpapers"))


-- ── Screenshots ───────────────────────────────────────────────
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m output -o ~/screenshots"))
hl.bind(S .. " + Print", hl.dsp.exec_cmd("hyprshot -m region --raw | satty -f - --copy-command wl-copy --output-filename ~/screenshots/$(date '+%Y%m%d-%H%M%S').png"))
hl.bind(SC .. " + Print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

-- ── Window Management ─────────────────────────────────────────
hl.bind(S .. " + Q", hl.dsp.window.close())
hl.bind(S .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(SS .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(S .. " + P", hl.dsp.window.pseudo())
hl.bind(SA .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(S .. " + O", hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", window = "active" }))

-- ── Focus (HJKL + arrows) ─────────────────────────────────────
hl.bind(S .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(S .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(S .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(S .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(S .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(S .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(S .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(S .. " + down", hl.dsp.focus({ direction = "down" }))

-- ── Move Window ───────────────────────────────────────────────
hl.bind(SS .. " + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(SS .. " + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(SS .. " + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(SS .. " + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(SS .. " + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(SS .. " + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(SS .. " + down", hl.dsp.window.move({ direction = "d" }))

-- ── Resize ────────────────────────────────────────────────────
hl.bind(SA .. " + right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
hl.bind(SA .. " + left", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
hl.bind(SA .. " + up", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
hl.bind(SA .. " + down", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })

-- ── Workspaces (1–4 visible by default) ───────────────────────
hl.bind(S .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(S .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(S .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(S .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(S .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(S .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(S .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(S .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(S .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(S .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(SS .. " + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(SS .. " + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(SS .. " + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(SS .. " + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(SS .. " + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(SS .. " + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(SS .. " + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(SS .. " + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(SS .. " + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(SS .. " + 0", hl.dsp.window.move({ workspace = 10 }))

-- ── Workspace Cycling ─────────────────────────────────────────
hl.bind(S .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(S .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(SC .. " + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(SC .. " + left", hl.dsp.focus({ workspace = "e-1" }))

-- ── Overview (Hyprswitch/Scrolloverview) ───────────────────────────
hl.bind(S .. " + TAB", function()
    pcall(function()
        hl.plugin.scrolloverview.overview("toggle all")
    end)
end)

-- ── Switch workspaces ────────────────────────────────────────────────
hl.bind(S .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(SS .. " + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- ── Mouse Binds ───────────────────────────────────────────────
hl.bind(S .. " + mouse:272", hl.dsp.window.drag())
hl.bind(S .. " + mouse:273", hl.dsp.window.resize())

-- ── Media Keys ────────────────────────────────────────────────
-- These adjust volume/brightness directly. ZenShell polls `wpctl` and
-- `brightnessctl` (zenshell/shell.qml) and draws its own theme-aware OSD, so
-- there is no need for swayosd-client here — and running both meant every
-- volume key flashed two overlapping overlays, one of them unstyled because
-- swayosd-server was starting with no config.yaml.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- ── Brightness ────────────────────────────────────────────────
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })

-- ── ZenShell Dynamic Island ───────────────────────────────────
-- Notification/control center is SUPER+N (plain, section above).
-- The rest live on SUPER+SHIFT since the primary UI binds now own
-- the plain SUPER+ keys.

hl.bind(S .. " + escape", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh power"))
hl.bind(SS .. " + P", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/island_ctl.sh powerprofile"))
hl.bind(SS .. " + M", hl.dsp.exec_cmd("~/.config/quickshell/dynamic-island/modules/spotlight/toggle.sh"))

-- ── System ────────────────────────────────────────────────────
hl.bind(SC .. " + R", hl.dsp.exec_cmd("hyprctl reload && notify-send \"Hyprland\" \"Config reloaded\""))
hl.bind(SC .. " + Q", hl.dsp.exit())

--Plugins
---- hyprland.lua

