#!/usr/bin/env python3
"""
Generate every HyprZen theme artifact from a single source of truth.

Source of truth:  .config/hypr/themes/source/<slug>.toml   (one file per theme)
Generated:        .config/hypr/themes/<slug>.lua           Hyprland  (Lua)
                  .config/hypr/themes/<slug>.conf          Hyprlang vars
                  .config/hypr/themes/<slug>.css           GTK / SwayOSD / wlogout
                  .config/kitty/themes/<slug>.conf         Kitty
                  ../../../../zenshell/scripts/themes.json  ZenShell island

Why: previously the palette lived in five independent places that drifted apart.
The shell picker, Hyprland, Kitty and GTK could all disagree about what "nord"
looks like. Now there is exactly one place to edit a colour.

Usage:
    python3 gen-themes.py            # regenerate everything
    python3 gen-themes.py --check    # exit 1 if anything is out of date (for CI)
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent          # hyprzen/scripts
CONFIG_DIR = SCRIPT_DIR.parent / ".config"
SOURCE_DIR = CONFIG_DIR / "hypr" / "themes" / "source"
HYPR_THEMES = CONFIG_DIR / "hypr" / "themes"
KITTY_THEMES = CONFIG_DIR / "kitty" / "themes"
REPO_ROOT = SCRIPT_DIR.parent.parent
ZENSHELL_JSON = REPO_ROOT / "zenshell" / "scripts" / "themes.json"
# theme-switch.sh reads the manifest from here, next to the theme files.
HYPR_MANIFEST = HYPR_THEMES / "themes.json"

BANNER = (
    "-- Generated by hyprzen/scripts/gen-themes.py from themes/source/{slug}.toml\n"
    "-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.\n"
)

# Geometry every theme must define; a missing key is a hard error rather than a
# silent fallback, because a half-defined theme is how we got here in the first place.
REQUIRED_GEOMETRY = {
    "rounding",
    "border_size",
    "gaps_in",
    "gaps_out",
    "blur_size",
    "blur_passes",
    "inactive_opacity",
    "shadow_color",
}
REQUIRED_COLORS = {"bg", "surface", "overlay", "accent", "fg", "subfg", "urgent"}
REQUIRED_PALETTE = {"black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"}


def strip_hash(value: str) -> str:
    return value.lstrip("#").lower()


def rgba(hex_color: str, alpha: float) -> str:
    """#rrggbb + alpha -> rgba(r,g,b,a) for CSS output."""
    h = strip_hash(hex_color)
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r}, {g}, {b}, {alpha:g})"


def hex8(hex_color: str, alpha: float) -> str:
    """#rrggbb + alpha -> rgba(rrggbbaa) for Hyprland colour values."""
    h = strip_hash(hex_color)
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r:02x}{g:02x}{b:02x}{round(alpha * 255):02x})"


def load_themes() -> list[dict]:
    themes: list[dict] = []
    for toml_path in sorted(SOURCE_DIR.glob("*.toml")):
        slug = toml_path.stem
        try:
            data = tomllib.loads(toml_path.read_text(encoding="utf-8"))
        except tomllib.TOMLDecodeError as exc:
            sys.exit(f"error: {toml_path.name} is not valid TOML: {exc}")

        for section, keys in (
            ("meta", {"name", "icon"}),
            ("colors", REQUIRED_COLORS),
            ("geometry", REQUIRED_GEOMETRY),
            ("palette", REQUIRED_PALETTE),
        ):
            present = set(data.get(section, {}))
            missing = keys - present
            if missing:
                sys.exit(f"error: {toml_path.name} [{section}] is missing: {', '.join(sorted(missing))}")

        data["meta"]["slug"] = data["meta"].get("slug", slug)
        if data["meta"]["slug"] != slug:
            sys.exit(f"error: {toml_path.name} declares slug '{data['meta']['slug']}'; filename says '{slug}'")
        data["_source"] = toml_path
        themes.append(data)

    if not themes:
        sys.exit(f"error: no theme sources found in {SOURCE_DIR}")
    return themes


def render_lua(theme: dict) -> str:
    c, g, m = theme["colors"], theme["geometry"], theme["meta"]
    body = "\n".join(
        [
            "",
            f'-- {m["name"]}',
            '---@module "hl"',
            "",
            f'bg = "{strip_hash(c["bg"])}"',
            "",
            f'surface = "{strip_hash(c["surface"])}"',
            "",
            f'overlay = "{strip_hash(c["overlay"])}"',
            "",
            f'accent = "{strip_hash(c["accent"])}"',
            "",
            f'text = "{strip_hash(c["fg"])}"',
            "",
            f'subtext = "{strip_hash(c["subfg"])}"',
            "",
            f'urgent = "{strip_hash(c["urgent"])}"',
            "",
            f'border_active = "{hex8(c["accent"], 1.0)}"',
            "",
            f'border_inactive = "{hex8(c["surface"], 0.65)}"',
            "",
            f"rounding = {g['rounding']}",
            "",
            f"border_size = {g['border_size']}",
            "",
            f"gaps_in = {g['gaps_in']}",
            "",
            f"gaps_out = {g['gaps_out']}",
            "",
            f"blur_size = {g['blur_size']}",
            "",
            f"blur_passes = {g['blur_passes']}",
            "",
            f'inactive_opacity = {g["inactive_opacity"]:.2f}',
            "",
            f'shadow_color = "{g["shadow_color"]}"',
            "",
        ]
    )
    return f'{BANNER.format(slug=m["slug"])}\n{body}'


def render_conf(theme: dict) -> str:
    """Hyprlang variable form, consumed by hyprlock and any classic .conf loader."""
    g = theme["geometry"]
    lines = [
        f"# {theme['meta']['name']} — generated from themes/source/{theme['meta']['slug']}.toml",
        "",
        f'$bg = {strip_hash(theme["colors"]["bg"])}',
        f'$surface = {strip_hash(theme["colors"]["surface"])}',
        f'$overlay = {strip_hash(theme["colors"]["overlay"])}',
        f'$accent = {strip_hash(theme["colors"]["accent"])}',
        f'$text = {strip_hash(theme["colors"]["fg"])}',
        f'$urgent = {strip_hash(theme["colors"]["urgent"])}',
        f'$border_active = {hex8(theme["colors"]["accent"], 1.0)}',
        f'$border_inactive = {hex8(theme["colors"]["surface"], 0.65)}',
        f'$rounding = {g["rounding"]}',
        f'$border_size = {g["border_size"]}',
        f'$gaps_in = {g["gaps_in"]}',
        f'$gaps_out = {g["gaps_out"]}',
        f'$blur_size = {g["blur_size"]}',
        f'$blur_passes = {g["blur_passes"]}',
        f'$inactive_opacity = {g["inactive_opacity"]:.2f}',
        f'$shadow_color = {g["shadow_color"]}',
        "",
    ]
    return "\n".join(lines)


def render_css(theme: dict) -> str:
    c = theme["colors"]
    lines = [
        f"/* {theme['meta']['name']} — generated from themes/source/{theme['meta']['slug']}.toml */",
        "",
        f'@define-color bg_base       {strip_hash(c["bg"])};',
        f'@define-color bg_surface    {rgba(c["surface"], 0.88)};',
        f'@define-color bg_overlay    {rgba(c["overlay"], 0.75)};',
        f'@define-color accent        {strip_hash(c["accent"])};',
        f'@define-color accent_soft   {rgba(c["accent"], 0.18)};',
        f'@define-color accent_glow   {rgba(c["accent"], 0.35)};',
        f'@define-color secondary     {strip_hash(c["accent"])};',
        f'@define-color text          {strip_hash(c["fg"])};',
        f'@define-color subtext       {strip_hash(c["subfg"])};',
        f'@define-color border_color  {rgba(c["accent"], 0.20)};',
        f'@define-color urgent        {strip_hash(c["urgent"])};',
        "",
    ]
    return "\n".join(lines)


def render_kitty(theme: dict) -> str:
    c, p, m = theme["colors"], theme["palette"], theme["meta"]

    def pal(name: str) -> str:
        return strip_hash(p[name])

    def bright(name: str, fallback: str) -> str:
        return strip_hash(p.get(f"bright_{name}", fallback))

    rows = [
        f"# {m['name']} — generated from themes/source/{m['slug']}.toml",
        "",
        f"background            {strip_hash(c['bg'])}",
        f"foreground            {strip_hash(c['fg'])}",
        f"selection_background  {strip_hash(c['accent'])}",
        f"selection_foreground  {strip_hash(c['bg'])}",
        f"cursor                {strip_hash(c['accent'])}",
        f"cursor_text_color     {strip_hash(c['bg'])}",
        f"url_color             {strip_hash(c['accent'])}",
        "",
        f"color0   {pal('black')}",
        f"color8   {bright('black', pal('white'))}",
        f"color1   {pal('red')}",
        f"color9   {bright('red', pal('red'))}",
        f"color2   {pal('green')}",
        f"color10  {bright('green', pal('green'))}",
        f"color3   {pal('yellow')}",
        f"color11  {bright('yellow', pal('yellow'))}",
        f"color4   {pal('blue')}",
        f"color12  {bright('blue', pal('blue'))}",
        f"color5   {pal('magenta')}",
        f"color13  {bright('magenta', pal('magenta'))}",
        f"color6   {pal('cyan')}",
        f"color14  {bright('cyan', pal('cyan'))}",
        f"color7   {pal('white')}",
        f"color15  {bright('white', pal('white'))}",
        "",
        f"active_tab_background   {strip_hash(c['accent'])}",
        f"active_tab_foreground   {strip_hash(c['bg'])}",
        f"inactive_tab_background {strip_hash(c['surface'])}",
        f"inactive_tab_foreground {strip_hash(c['fg'])}",
        "",
    ]
    return "\n".join(rows)


def render_zenshell(themes: list[dict]) -> str:
    payload = [
        {
            "id": t["meta"]["slug"],
            "name": t["meta"]["name"],
            "icon": t["meta"]["icon"],
            "accent": t["colors"]["accent"],
            "bg": t["colors"]["bg"],
            "surface": t["colors"]["surface"],
            "fg": t["colors"]["fg"],
            "extra": t["colors"]["urgent"],
            "dark": t["meta"].get("dark", True),
            "rounding": t["geometry"]["rounding"],
        }
        for t in themes
    ]
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def build(theme: dict) -> dict[str, str]:
    slug = theme["meta"]["slug"]
    return {
        HYPR_THEMES / f"{slug}.lua": render_lua(theme),
        HYPR_THEMES / f"{slug}.conf": render_conf(theme),
        HYPR_THEMES / f"{slug}.css": render_css(theme),
        KITTY_THEMES / f"{slug}.conf": render_kitty(theme),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files are current; do not write")
    args = parser.parse_args()

    themes = load_themes()
    outputs: dict[Path, str] = {}
    for theme in themes:
        outputs.update(build(theme))
    outputs[ZENSHELL_JSON] = render_zenshell(themes)
    outputs[HYPR_MANIFEST] = render_zenshell(themes)

    if args.check:
        stale = [
            str(path.relative_to(REPO_ROOT))
            for path, content in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("gen-themes: generated files are out of date:", file=sys.stderr)
            for path in sorted(stale):
                print(f"  {path}", file=sys.stderr)
            print("\nRun: python3 hyprzen/scripts/gen-themes.py", file=sys.stderr)
            return 1
        print(f"gen-themes: {len(themes)} themes, {len(outputs)} generated files, all up to date.")
        return 0

    for path, content in sorted(outputs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    print(f"gen-themes: wrote {len(outputs)} files for {len(themes)} themes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
