-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ! Auto-generated file. Do not edit directly.

-- Remove source = ./dms/colors.conf from your config to override.

primary = "rgb(d0bcff)"

outline = "rgb(948f99)"

error = "rgb(f2b8b5)"

hl.config({
    general = {
        col = {
            active_border = "rgb(d0bcff)",
            inactive_border = "rgb(948f99)",
        },
    },
})

hl.config({
    group = {
        groupbar = {
            ["col.active"] = "rgb(d0bcff)",
            ["col.inactive"] = "rgb(948f99)",
            ["col.locked_active"] = "rgb(f2b8b5)",
            ["col.locked_inactive"] = "rgb(948f99)",
        },
        col = {
            border_active = "rgb(d0bcff)",
            border_inactive = "rgb(948f99)",
            border_locked_active = "rgb(f2b8b5)",
            border_locked_inactive = "rgb(948f99)",
        },
    },
})
