-- Generated by hyprzen/scripts/gen-themes.py from themes/source/aetheria.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Aetheria
---@module "hl"

bg = "fafafa"

surface = "f0f0f0"

overlay = "e5e5e5"

accent = "7287fd"

text = "4c4f69"

subtext = "6c6f85"

urgent = "ea76cb"

border_active = "rgba(7287fdff)"

border_inactive = "rgba(f0f0f0a6)"

rounding = 18

border_size = 2

gaps_in = 6

gaps_out = 16

blur_size = 8

blur_passes = 3

inactive_opacity = 0.94

shadow_color = "rgba(00000029)"
