-- Generated by hyprzen/scripts/gen-themes.py from themes/source/alabaster.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Alabaster
---@module "hl"

bg = "f7f7f7"

surface = "ffffff"

overlay = "eeeeee"

accent = "555555"

text = "434343"

subtext = "6b6b6b"

urgent = "aa3731"

border_active = "rgba(555555ff)"

border_inactive = "rgba(ffffffa6)"

rounding = 12

border_size = 1

gaps_in = 5

gaps_out = 12

blur_size = 3

blur_passes = 2

inactive_opacity = 0.95

shadow_color = "rgba(0000001f)"
