-- Generated by hyprzen/scripts/gen-themes.py from themes/source/dynamic.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Dynamic (pywal)
---@module "hl"

bg = "15180a"

surface = "15180a"

overlay = "696d59"

accent = "90aa22"

text = "ebdbb2"

subtext = "bdae93"

urgent = "fb4934"

border_active = "rgba(90aa22ff)"

border_inactive = "rgba(15180aa6)"

rounding = 12

border_size = 2

gaps_in = 5

gaps_out = 12

blur_size = 4

blur_passes = 2

inactive_opacity = 0.92

shadow_color = "rgba(00000066)"
