-- Generated by hyprzen/scripts/gen-themes.py from themes/source/eva-theme.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Eva Theme
---@module "hl"

bg = "1a0033"

surface = "26004d"

overlay = "0d001a"

accent = "9ece6a"

text = "c0caf5"

subtext = "a9b1d6"

urgent = "ff5370"

border_active = "rgba(9ece6aff)"

border_inactive = "rgba(26004da6)"

rounding = 4

border_size = 2

gaps_in = 4

gaps_out = 8

blur_size = 4

blur_passes = 2

inactive_opacity = 0.92

shadow_color = "rgba(0000008c)"
