-- Generated by hyprzen/scripts/gen-themes.py from themes/source/gruvbox.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Gruvbox
---@module "hl"

bg = "282828"

surface = "3c3836"

overlay = "1d2021"

accent = "d79921"

text = "ebdbb2"

subtext = "d5c4a1"

urgent = "fb4934"

border_active = "rgba(d79921ff)"

border_inactive = "rgba(3c3836a6)"

rounding = 8

border_size = 2

gaps_in = 4

gaps_out = 8

blur_size = 3

blur_passes = 2

inactive_opacity = 0.92

shadow_color = "rgba(00000073)"
