-- Generated by hyprzen/scripts/gen-themes.py from themes/source/lavender.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Lavender
---@module "hl"

bg = "1a1525"

surface = "221b33"

overlay = "120e1a"

accent = "b4befe"

text = "c8d3f5"

subtext = "a5abd8"

urgent = "ff757f"

border_active = "rgba(b4befeff)"

border_inactive = "rgba(221b33a6)"

rounding = 20

border_size = 2

gaps_in = 6

gaps_out = 16

blur_size = 8

blur_passes = 3

inactive_opacity = 0.92

shadow_color = "rgba(0000008c)"
