-- Generated by hyprzen/scripts/gen-themes.py from themes/source/matugen.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Matugen
---@module "hl"

bg = "131318"

surface = "1f1f25"

overlay = "47464f"

accent = "c2c1ff"

text = "e4e1e9"

subtext = "c8c5d0"

urgent = "ffb4ab"

border_active = "rgba(c2c1ffff)"

border_inactive = "rgba(1f1f25a6)"

rounding = 14

border_size = 2

gaps_in = 5

gaps_out = 14

blur_size = 5

blur_passes = 3

inactive_opacity = 0.93

shadow_color = "rgba(0000008c)"
