-- Generated by hyprzen/scripts/gen-themes.py from themes/source/noir.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Noir
---@module "hl"

bg = "0f0f0f"

surface = "141414"

overlay = "1a1a1a"

accent = "838996"

text = "c0c0c0"

subtext = "8a8a8a"

urgent = "c23b3b"

border_active = "rgba(838996ff)"

border_inactive = "rgba(141414a6)"

rounding = 0

border_size = 1

gaps_in = 0

gaps_out = 0

blur_size = 2

blur_passes = 2

inactive_opacity = 0.85

shadow_color = "rgba(00000000)"
