-- Generated by hyprzen/scripts/gen-themes.py from themes/source/nord.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Nord
---@module "hl"

bg = "2e3440"

surface = "3b4252"

overlay = "242933"

accent = "88c0d0"

text = "d8dee9"

subtext = "e5e9f0"

urgent = "bf616a"

border_active = "rgba(88c0d0ff)"

border_inactive = "rgba(3b4252a6)"

rounding = 10

border_size = 2

gaps_in = 5

gaps_out = 12

blur_size = 4

blur_passes = 2

inactive_opacity = 0.92

shadow_color = "rgba(00000059)"
