-- Generated by hyprzen/scripts/gen-themes.py from themes/source/one-dark.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- One Dark
---@module "hl"

bg = "282c34"

surface = "21252b"

overlay = "1b1d23"

accent = "61afef"

text = "abb2bf"

subtext = "9da5b4"

urgent = "e06c75"

border_active = "rgba(61afefff)"

border_inactive = "rgba(21252ba6)"

rounding = 8

border_size = 1

gaps_in = 4

gaps_out = 10

blur_size = 4

blur_passes = 2

inactive_opacity = 0.92

shadow_color = "rgba(00000066)"
