-- Generated by hyprzen/scripts/gen-themes.py from themes/source/osaka-jade.toml
-- DO NOT EDIT BY HAND — edit the TOML source and re-run the generator.


-- Osaka Jade
---@module "hl"

bg = "0f1715"

surface = "18221f"

overlay = "080c0b"

accent = "1db954"

text = "d3c6aa"

subtext = "9da9a0"

urgent = "e67e80"

border_active = "rgba(1db954ff)"

border_inactive = "rgba(18221fa6)"

rounding = 14

border_size = 2

gaps_in = 5

gaps_out = 12

blur_size = 5

blur_passes = 3

inactive_opacity = 0.93

shadow_color = "rgba(00000080)"
